###服务端口号
server:
  port: 8006

spring:
  application:
    name: cloud-provider-consul-payment
  ###consul注册中心地址
  cloud:
    consul:
      host: 192.168.0.135
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}
