server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://192.168.0.135:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Perfect1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenren.springcloud.entities #所有Entity别名类所在包

